import type { AuthKitMessages } from "../types/config";

export const DEFAULT_MESSAGES: Required<AuthKitMessages> = {
  networkError: "네트워크 오류가 발생했습니다. 인터넷 연결을 확인해주세요.",
  back: "돌아가기",
  backToLogin: "로그인으로 돌아가기",
  or: "또는",
  labelName: "이름",
  labelEmail: "이메일",
  labelPassword: "비밀번호",
  labelPasswordConfirm: "비밀번호 확인",
  labelNewPassword: "새 비밀번호",
  labelNewPasswordConfirm: "새 비밀번호 확인",
  placeholderName: "홍길동",
  placeholderEmail: "example@email.com",
  placeholderPassword: "비밀번호를 입력하세요",
  placeholderPasswordSignup: "8자 이상, 대문자·특수문자 포함",
  placeholderPasswordConfirm: "비밀번호를 다시 입력하세요",
  btnLogin: "로그인",
  btnSignup: "회원가입",
  btnSignupSubmit: "가입하기",
  btnForgotPassword: "비밀번호를 잊으셨나요?",
  btnGoogleLogin: "Google로 계속하기",
  btnSendOtp: "인증 코드 보내기",
  btnResendOtp: "코드 재전송",
  btnChangePassword: "비밀번호 변경",
  emailRequired: "이메일을 입력해주세요.",
  passwordRequired: "비밀번호를 입력해주세요.",
  accountNotFound: "존재하지 않는 계정입니다.",
  passwordWrong: "비밀번호가 일치하지 않습니다.",
  emailAlreadyRegistered: "이미 가입된 이메일입니다.",
  agreeRequired: "이용약관과 개인정보처리방침에 동의해주세요.",
  otpExpired: "인증 코드가 만료되었습니다. 다시 요청해주세요.",
  otpInvalid: "인증 코드가 올바르지 않습니다.",
  resendFailed: "재전송에 실패했습니다. 인터넷 연결을 확인해주세요.",
  timerExpired: "만료됨",
  otpTitle: "인증 코드 입력",
  otpSubtitleSuffix: "으로\n6자리 코드를 보냈습니다.",
  forgotPasswordTitle: "비밀번호 찾기",
  forgotPasswordSubtitle: "가입한 이메일을 입력하시면\n인증 코드를 보내드립니다.",
  resetPasswordTitle: "새 비밀번호 설정",
  resetPasswordSubtitle: "새로운 비밀번호를 입력해주세요.",
  passwordChangedTitle: "비밀번호가 변경되었습니다!",
  passwordChangedSubtitle: "새 비밀번호로 로그인해주세요.",
  termsAgreeAll: "전체 동의",
  termsAgreeTos: "이용약관 동의 (필수)",
  termsAgreePrivacy: "개인정보처리방침 동의 (필수)",
  termsView: "보기",
  vNameRequired: "이름을 입력해주세요.",
  vNameMin: "이름은 2자 이상이어야 합니다.",
  vEmailRequired: "이메일을 입력해주세요.",
  vEmailInvalid: "올바른 이메일 형식이 아닙니다.",
  vPasswordRequired: "비밀번호를 입력해주세요.",
  vPasswordMin: "비밀번호는 8자 이상이어야 합니다.",
  vPasswordUppercase: "대문자를 포함해야 합니다.",
  vPasswordSpecial: "특수문자를 포함해야 합니다.",
  vPasswordConfirmRequired: "비밀번호를 다시 입력해주세요.",
  vPasswordConfirmMatch: "비밀번호가 일치하지 않습니다.",
  pwRuleMin: "8자 이상",
  pwRuleUppercase: "대문자 포함",
  pwRuleSpecial: "특수문자 포함",
};

export const OTP_DURATION = 180;
export const OTP_LENGTH = 6;
export const FOCUS_DELAY = 100;
export const PASSWORD_MIN_LENGTH = 8;
export const SPECIAL_CHAR_REGEX = /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/;
